INSTALL.md

.htaccess file and another . directory. Without these instructions,
the Checkbook installation simply won't work. (The .htaccess file
contains necessary URI rewrite directives.)
Second, added links for an alternate method of installing Drush
(as found on the Drush project page). The pear method no longer
works.
Third, made some minor documentation formatting changes.

First, added important instructions about copying the Checkbook

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/home/top_slider/472.json

[NYCCHKBK-7557](https://tracker.reisys.com/browse/NYCCHKBK-7557) - Reverting only necessary changes for the vendor name exact filter in the contracts advanced search result, top navigation.
Saroja,
I only reverted changes I made to the top navigation to filter by the vendor name.  I have verified the issue raised here: [(NYCCHKBK-7635)](https://tracker.reisys.com/browse/NYCCHKBK-7635) is now fixed
Please verify that your changes still work.
Files Reverted:
source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/home/top_slider/472.json
You already reverted these, so I did not need to:
source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contracts_navigation.tpl.php 
Files …

NYCCHKBK-7557 - Peer Review Request

---

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module

- Advanced Search: 
- Data Feeds:

Fix: Contracts Advanced Search- Status Order Mismatch

---

source/webapp/sites/all/modules/custom/checkbook_export/includes/checkbook_export.inc

Tried PHP pqsql escape functions. It is not working for 'copy' command where as it is working for DB query.

NYCCHKBK-9166: Escaping double quotes in where parameter

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/WidgetUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contract/nycha_contract_details.tpl.php
source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_domain/config/sql/spending/nycha_spending.xml
source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_presentation_layer/checkbook_views/checkbook_view_configs/landing_page_widgets/nycha_spending/nycha_contracts_view.json
source/webapp/sites/all/themes/checkbook3/css/global.css

Add billed amount column to nycha spending landing page top 5 contracts widget.

Feature/nycchkbk 9287- Add billed amount column nycha spending

---

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_across_years.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_1.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_2.json
source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/nychaSpending/NychaSpendingWidgetService.php

Updated links for nycha spending visualizations vendor and contract id links.
Contract id opens in new window and shows contract details.
Vendor id filters data for particular id and chart is not displayed for vendor id.
Updated the drupal configurations to show the correct charts for the category choosen. Please build and verify.

NYCCHKBK -9361  Nycha spending hyperlinks for vendor and contract id charts

---

source/webapp/sites/all/modules/custom/checkbook_faceted_search/css/narrow-down-filter.css

Tested in both chrome and firefox.

 Document id display issue narrow down filters in firefox  fix

---

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/310.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/317.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/330.json
source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/payroll.tpl.php
source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook/cube-payroll.json
source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook/cube-payroll_employee_agency.json
source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook_nycha/cube-payroll.json
source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook_nycha/cube-payroll_employee_agency_basis.json

Payroll - Citywide 
1) Hourly and daily is show in the one column. When both hourly and daily data is null  or data is less than zero display '-' in both transactions and exports.
2) Smart search display also modified to show above change.
3) All the related pages also verified and updated accordingly.
Payroll Nycha
1) hourly and daily data is shown in 2 separate columns. Display hyphen when there is null data or data is less than 0. Export also dispay accordingly.
2) Verified the related pages and updated accordingly.

Feature/nycchkbk 9257 - Payroll - hourly and daily rate display for citywide and nycha.

---

source/webapp/sites/all/modules/custom/checkbook_solr/config/nycha.json

Vendor name auto-complete (main search bar) should be mapped with 'vendor_name_search' Solr field as N/A changes are implemented in it.

NYCCHKBK-9596: NYCHA auto-complete mapping for vendor

---

source/webapp/sites/all/modules/custom/checkbook_faceted_search/smart_search_filter.tpl.php
source/webapp/sites/all/modules/custom/checkbook_smart_search/includes/checkbook_smart_search.inc
source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/nycha_contracts.tpl.php
source/webapp/sites/all/modules/custom/checkbook_solr/config/citywide.json

Smart Search exports
Nycha Contracts - hyphen display for fields based on record type, hyphen display for agreement type 'purchase order.
Nycha Spending - hyphen display for agreement types  and  certain amount values if null
Nycha Payroll - hyphen display for hourly , daily and annual salary when null or less than zero
Citywide Payroll -  display daily wage when  hourly rate is zero or display '-' when both are null or less than zero. 
Smart search results
nycha contracts results to display hyphen based on record types.

Feature/nycchkbk 9132 - Smart search export results and nycha contracts '-' display for record type. 

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php
source/webapp/sites/all/modules/custom/checkbook_solr/src/checkbook_solr_query.class.inc

The issue is 801ge without space gives correct results, but add a space to the term it shows all the results. This issue only exist in advanced search. Data-feeds looks fine for both the scenario.

Feature/nycchkbk 9920 - Advanced search results for terms with space.

---

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_revenue/transactions_page_widgets/1051.json
source/webapp/sites/all/themes/checkbook3/css/global.css

Reduce left margin (from 15px to 10px) of first column heading for all transaction data tables. This is to fit two words in one line for the first column heading.

Reduce left margin of first column heading in transaction data tables

---

source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/payroll.tpl.php

Update year type (from C to B) in Smart Search Citywide Payroll agency links to redirect and display FY

Update year type to display FY

---

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Advanced Search Payroll section: Rectify the ID selector for capturing value of agency field (code) which acts a filter to fetch the list of keywords (for autocomplete) for 'Title' field.

Rectify the ID selector for capturing agency

---

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contracts_navigation.tpl.php

Reverts NYCComptroller/Checkbook#2132 
Had to revert to refactor this because of NYCCHKBK-10182
https://tracker.reisystems.com/browse/NYCCHKBK-10182

Revert "feature - NYCCHKBK - 8824 - Citywide top navigation disabling when there is no data."

---

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module
source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php
source/webapp/sites/all/modules/custom/checkbook_project/customclasses/budget/NychaBudgetUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_budget/1043.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_budget/1044.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_budget/transactions_page_widgets/1034.json

1) Disable null value display in facets and display only 'n/a' as 'n/a' in facets.
2) Display 'n/a' as 'n/a' and null as null for budget_type and budget_name in Nycha budget transactions
3) Remove null values from drop downs for budget_type and budget_name fields in datafeeds and advance search forms.

Feature nycchkbk 10215 - Nycha budget - budget_name and budget_type factes and transactions page update.

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/revenue/NychaRevenueUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_revenue/1059.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_revenue/1060.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_revenue/transactions_page_widgets/1051.json

1. Disable null value display in facets and display only 'n/a' as 'n/a' in facets.
2. Display 'n/a' as 'n/a' and null as null for budget_type and budget_name in Nycha budget transactions

Feature nycchkbk 10302 - Nycha revenue 'n/a' and null value display update for budget_type and budget_name columns.

---

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Add 'year' and 'catastrophic event' filter enable/disable functionality for special cases as follows:
1. If expense category is 'Payroll' or 'Others', no matter which year is selected, the catastrophic event filter will remain disabled.
2. If catastrophic event filter has 'covid-19' selected, and then one selects expense category as 'Payroll' or 'Others', then the year filter will show all options in dropdown (which were limited due to 'covid-19') whereas keeping the selected year option as it is.
3. If expense category is other than 'Payroll' & 'Others', and the year filter selected option is neither of 'FY 2020', or 'FY 2021' or 'All years', then catastrophic event filter will remain disabled.

NYCCHKBK-10322 Advanced Search Form - Spending - Year filter is not refreshed

---

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Refresh 'Revenue class' and 'Revenue source' when 'covid-19' is selected in Catastrophic events drop-down. Remove handling for auto-complete fields that don't exist in the form.

NYCCHKBK-10310 : Advance Search Form Revenue - Revenue Source and Class not updated

---

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module
source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/spending.js

**Handled the following concerns:**
- When 'previous' button is clicked from data feeds results page, form fields data is restored correctly, but the form fields that were 'disabled’ or whose ‘options were limited' because of other dropdown filters aren't restored correctly.
- When ‘year filter’ changes, if spending category is ‘payroll’ or ‘others’, keep catastrophic event filter disabled, no matter which year is selected.

NYCCHKBK-10321: Datafeeds - Spending - Date filter list all years FY2011 to FY2021 for COVID19 dropdown 

---

source/webapp/sites/all/modules/custom/checkbook_api/handler/XMLDataHandler.php

Handle 'CASE' statements in 'SELECT' query for XML for COVID branch

NYCCHKBK-10332: Datafeeds - Spending - No Results found for download data [COVID]

---

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/contracts/checkbook_datafeeds_contracts.inc
source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/RevenueFeedCitywide.class.inc
source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedCitywide.class.inc

Handled scenarios where catastrophic event filter:
1. Gets disabled due to some selection. For example, in spending data feeds, Spending Category: Others [o] will disable catastrophic event filter
2. Has default option 'Select Event' selected

[COVID] NYCCHKBK-10382- Data-Feeds Spending, Revenue and Contracts Catastrophic Event field issue

---

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Since data source / domain options (nycha, citywide) are hidden, added an explicit call to data source change function which eventually initializes autocomplete and other important aspects of the form.

[COVID] NYCCHKBK-10291: Advanced search form Revenue - autocompletes not working

---

source/tests/functional/NYCAutomationTest/pom.xml

Jenkins build failed with error:
cannot access org.openqa.selenium.WrapsElement
class file for org.openqa.selenium.WrapsElement not found
Found a similar error & solution here: https://stackoverflow.com/questions/52992915/selenium-selenide-class-file-for-org-openqa-selenium-wrapsdriver-not-found-for
Updating the pom.xml to add selenium-api repo for dependency

Possible fix for Selenium testing issue

---

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe_subvendors/757.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/sub-vendors/723.json

- Add 'Woman owned business' and 'Emerging business' columns to spending transaction pages
- Add Native and Emerging MWBE categories in queries
- Respective cube file for export columns have already been updated (https://github.com/NYCComptroller/Checkbook/pull/2361/files)

Feature NYCCHKBK-10505: MWBE changes for Spending transaction pages

---

source/webapp/sites/all/modules/custom/checkbook_api_ref/checkbook_api_ref.info
source/webapp/sites/all/modules/custom/checkbook_api_ref/checkbook_api_ref.install
source/webapp/sites/all/modules/custom/checkbook_api_ref/checkbook_api_ref.module
source/webapp/sites/all/modules/custom/checkbook_api_ref/config/ref_file_sql.json
source/webapp/sites/all/modules/custom/checkbook_api_ref/includes/CheckbookApiRef.class.php
source/webapp/sites/all/modules/custom/checkbook_api_ref/theme/api-ref.email.tpl.php

1) The code has been refactored to generate only csv files . Issue with generating codes correctly with leading zeros has been fixed. 
2) The old module has not been deleted yet.
3) Need to enable the module in the drupal page once the code is pushed and also eventually disable the old module also.
4) Need to verify if the files are getting generated correctly in dev environment. Verification done only in local.

Feature nycchkbk 9894 - API Ref file generation module refactor to generate csv files only.

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php

- When $where_filter is empty, syntax error comes up. This pull request solves the same.

Defect NYCCHKBK-10424: Add spacing in SQL query to solve syntax error for special case in top navigation SQL query

---

source/webapp/sites/all/modules/custom/checkbook_smart_search/includes/checkbook_smart_search.inc

Refactoring the smart search export results to use fputcsv to write the results. Verified the hyphens display for various nycha contracts, spending and payroll(nycha and citywide), the budget code with parenthesis for citywide spending .Also fixed the edc entity contract number to display the comma correctly when the csv file is opened in excel.

Feature nycchkbk 9832 - Smartsearch export refactoring.

---

source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/spending_advanced_search.inc
source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Solves two issues:
1. Expense category drop down has “Payroll summary” which has code “0” which is the same as default “0”, resulting in drop down changing value to “Payroll summary” unexpectedly just after the nycha spending form loads.
2. Payroll summary having code “0” results in it being skipped from filters in advanced search spending transactions page.

defect NYCCHKBK-10579 : NYCHA Spending Advanced Search Expense Category drop down issue

---

source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/spending_advanced_search.inc
source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Solves two issues:
1. Expense category drop down has “Payroll summary” which has code “0” which is the same as default “0”, resulting in drop down changing value to “Payroll summary” unexpectedly just after the nycha spending form loads.
2. Payroll summary having code “0” results in it being skipped from filters in advanced search spending transactions page.

feature NYCCHKBK-10579 : NYCHA Spending Advanced Search Expense Category drop down issue

---

source/webapp/sites/all/modules/custom/checkbook_api_ref/includes/CheckbookApiRef.class.php

Since Sunday is considered as the first day of the week (when week changes), so modify logic to run cron on 'DEV' every monday.

Feature NYCCHKBK 9894 : Modify logic for cron timeline

---

source/webapp/sites/all/modules/custom/checkbook_api_ref/includes/CheckbookApiRef.class.php

Modify API ref cron time line to allow it to run it only between 9:00 am to 10:59 am  in order to keep it in the same time frame as other emails

Feature nycchkbk 9894: Modify API ref cron time line

---

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/contracts/checkbook_datafeeds_contracts.inc
source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/contracts.js
source/webapp/sites/all/themes/checkbook3/js/advanced-search.js

Reset and disable the following fields when 'pending' is selected as contract status for data feeds and/or advanced search (wherever the respective fields are not handled):
- Contract includes sub vendors
- Subvendors status in PIP
- Catastrophic event
- Year

Defect nycchkbk 10681 : Data feeds/Advanced Search Citywide Contracts Pending - Reset default fields

---

source/webapp/sites/all/modules/custom/checkbook_export/includes/checkbook_export.inc
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe/706.json

Refactored the checkbook_export to apply the alias column filed modification only when the query has alias column. Verified transactions exports with and without alias columns for correct export download.

Feature nycchkbk 11005 - Display 'n/a' for spending details transactions similar to results .

---

source/webapp/sites/all/modules/custom/checkbook_custom_breadcrumbs/customclasses/checkbook_custom_breadcrumbs.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/contracts/transaction_page_widgets/expense/939.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/contracts/transaction_page_widgets/expense/962.json

Verified mocs column displayed for advanced search when covid filter is applied.

Feature nycchkbk 11016 - Remove mocs column from details transactions results /exports. Update breadcrumbs title.

---

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/SpendingUtil.php
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/766.json

The title does not display correctly from payee name link in advanced search when the category filter is at the end of the url parameters because title display uses _getLastRequestParamValue().

Feature nycchkbk 11155(update) - Title not displaying correctly when category filter is in the end of url parameter.

---

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/1066.json
source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/mwbe/1065.json
source/webapp/sites/all/modules/dashboard_platform/data_controller_datasource/sql/core/query/datasource/operator/handler/SQL_NotEqualOperatorHandler.php

The query takes care of not null values in the facet. This works fine when the datatype is integer. When the data type is string not null checks only for null values. To check empty the query has to be update accordingly. The fix below handles the issue. 
To check for null use NotEmptyOperatorHandler. To check for empty use NotEqualOperatorHandler ( especially when the datatype is string).

Feature nycchkbk 11004(update) - Budget code facet to not display empty values.

---

source/webapp/sites/all/modules/custom/checkbook_api/criteria/XMLSearchCriteria.php

Verified - data load and size for all domains/data-sources (20k is the maximum limit for Postman and REST client)

NYCCHKBK-11310: Increased max record limit to 20k for API response
