source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_presentation_layer/checkbook_views/checkbook_view_configs/landing_page_widgets/revenue/funding_classes/revenue_by_funding_classes_by_cross_year_collections_view.json
Please review this change, let me know if there is anything you would like to add or change.
=> NYCCHKBK-7536 - Capitalized the C

source/webapp/sites/all/modules/custom/checkbook_advanced_search/config/checkbook_advanced_search_field_definitions.json, source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module
- Advanced Search: 
- Data Feeds:
=> Fix: Contracts Advanced Search- Status Order Mismatch

documentation/TESTING.md
Add a file documenting how to run Selenium tests on the `develop` branch.  
This is my understanding of how testing currently works.  I'm happy to update this file with corrections as needed.
=> Add TESTING.md file

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/common/VendorService.php
Pull request for NYCCHKBK-8032: [DEFECT] Vendor Navigation issues - CONTRACTS
=> NYCCHKBK-8032: Fix for Vendor Navigation issues - CONTRACTS

source/webapp/sites/all/modules/contrib/coder/coder_sniffer/Drupal/ruleset.xml, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_infrastructure_layer/constants/CommonConstants.php, source/webapp/sites/all/modules/custom/widget_framework/widget_data_tables/data_tables/1.9.0/media/unit_testing/tests_onhold/1_dom/oLanguage.sProcessing.js, source/webapp/sites/all/modules/custom/widget_framework/widget_data_tables/data_tables/1.9.0/media/unit_testing/tests_onhold/3_ajax/bProcessing.js
=> fixed whitespaces

source/webapp/sites/all/modules/contrib/coder/coder_sniffer/Drupal/ruleset.xml, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/SpendingUtil.php
=> fixed rules

source/webapp/sites/all/modules/custom/checkbook_project/includes/checkbook_project.inc, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contract/contract_vendor_info.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contract/contracts_mma_details.tpl.php
fixed the behavior of links for prime vendor , agency and mwbe category
=> fixed the behavior of links

source/webapp/sites/all/modules/custom/checkbook_trends/templates/revenue_capacity_trends/property_tax_levies.tpl.php, source/webapp/sites/all/modules/custom/checkbook_trends/templates/revenue_capacity_trends/property_tax_levies_csv.tpl.php
Changed `2016` to `2017` in table head
=> [NYCCHKBK-8211] [NYCCHKBK-8276] Property Tax Levies and Collections Trend

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/766.json
Reverts NYCComptroller/Checkbook#247
We need to revert these changes as requested by QA.
=> Revert "NYCCHKBK-8166: Fixed [DEFECT]Spending 'All pages' export issue"

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/contracts/transaction_page_widgets/expense/642.json
Fix bug introduced by PR #154 :: Contracts OGE transactions:child contracts are not loading
=> [NYCCHKBK-8308] [BugFix] Contracts OGE transactions:child contracts are not loading

source/tests/unit/tests/RequestUtilTest.php, source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/569.json, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/budget/BudgetUrlService.php, source/webapp/sites/all/modules/custom/widget_framework/widget_data_tables/widget_data_tables.module, source/webapp/sites/all/themes/checkbook3/css/global.css
1.Go To Advanced search > Budget 
2. Click on submit 
"Transactions" missing from the Title 
Current: Expense Budget 
Expeced: Expense Budget Transactions 
https://uat-checkbook-nyc.reisys.com/budget/transactions/year/119 
https://www.checkbooknyc.com/budget/transactions/year/119
=> [NYCCHKBK-8325] Fix 'Expense Budget Transactions' title

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_domain/config/sql/payroll/payroll.xml, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/payroll/data/IPayrollDataService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/payroll/data/PayrollDataService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_presentation_layer/checkbook_views/checkbook_view_configs/landing_page_widgets/payroll/agencies/agencies_by_overtime_view.json
Reverts NYCComptroller/Checkbook#323
=> Revert "NYCCHKBK-8216: Fixed [DEFECT] Payroll Overtime Widget Issue"

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/516.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/517.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/518.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/519.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/520.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/521.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/587.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/588.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/589.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/767.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/768.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/771.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/772.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/849.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/850.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/851.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/852.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/854.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/855.json, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsUrlService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsWidgetService.php
=> NYCCHKBK-8364: Formatting Json files

source/webapp/sites/all/modules/contrib/uuid/uuid.info, source/webapp/sites/all/modules/contrib/uuid/uuid_path/uuid_path.info, source/webapp/sites/all/modules/contrib/uuid/uuid_services/uuid_services.file_services.test, source/webapp/sites/all/modules/contrib/uuid/uuid_services/uuid_services.info, source/webapp/sites/all/modules/contrib/uuid/uuid_services/uuid_services.module, source/webapp/sites/all/modules/contrib/uuid/uuid_services_example/uuid_services_example.info
=> Universally Unique IDentifier - security update

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/contracts.js
Reverts NYCComptroller/Checkbook#502
=> Contracts multi-select Issue

source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/checkbook_advanced_search.inc, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_infrastructure_layer/constants/CommonConstants.php
Constructs the URL for nycha Contracts based on the input by the users
=> NYCCHKBK-8812:

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_2.json
This reverts commit 420350ee9347515187af1b452a22ff7aaf577507.
=> Revert "NYCCHKBK-8967 nycha contract id link title (#1001)"

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1012.json
Fixed display issue for nycha spending. Display '-' for columns with no data nycha spending.
=> NYCCHKBK-9146 Display '-' for columns with no data nycha spending.

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_domain/config/sql/spending/nycha_spending.xml
NYCCHKBK-9224 Update sql query for nycha-spending checks
=> NYCCHKBK-9224 Update sql query for nycha-spending checks

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1012.json
Added sort column for default sorting.
=> NYCCHKBK-9220 - Added sort column for default sorting.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1012.json
Default sorting to issue date and added document_id to sortSourcebyNull
=> NYCCHKBK-9220 - Default sorting to issue date nycha spending.

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_domain/config/sql/spending/nycha_spending.xml
Update query for nycha spending expense category to remove duplicates.
=> Feature/nycchkbk 9237- nycha spending expense category query update

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contract/nycha_contract_details.tpl.php
Nycha contracts transactions theming
=> NYCCHKBK-9313 Nycha contracts transactions theming

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/nychaSpending/NychaSpendingWidgetService.php
NYCCHKBK-9318 - Remove ytd links only for nycha spending section 8 category. (Industry, Funding source and expense categories)
=> NYCCHKBK-9318 - Remove ytd links only for nycha spending section 8 

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php, source/webapp/sites/all/themes/checkbook3/css/global.css
NYCCHKBK 9313 - Updated the information icon for nycha spending transactions static amount.
=> NYCCHKBK 9313 - Updated the information icon for nycha spending 

source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php
NYCCHKBK 9283 - Contracts id facet is pre selected, and also show associated data in facets.
=> NYCCHKBK 9283 - Nycha spending ytd links contracts facets issue.

source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php
NYCCHKBK - 9307 - Facet search document id filter display N/A for null values.
=> NYCCHKBK - 9307 - Facet search document id filter display N/A for null

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_3.json
NYCCHKBK - 9042- Adjust legend location, added comma to tooltip numbers nycha contracts years comparision by agreement types.
=> NYCCHKBK - 9042-Nycha Contracts visulizations - adjust legend location, added comma to tooltip numbers

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php, source/webapp/sites/all/themes/checkbook3/css/global.css
1) Fixed the theming for nycha contracts invoiced amount link in one line.
2) Added information icon to nycha amount spent.
=> Feature/nycchkbk 9092 - nycha contracts invoiced amount link static data theming and update.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_4.json
NYCCHKBK - 9236 Nycha contract visualization top 10 responsibility centers by current amount.
=> NYCCHKBK - 9236 Nycha contract visualization top 10 responsibility centers

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contract/nycha_contract_details.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/nychaContracts/NychaContractsUrlService.php
Nycha contract invoiced amount link for contract id details page implemented.
=> NYCCHKBK - 9092 Nycha contract invoiced amount link for contract id.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_across_years.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_1.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_2.json, source/webapp/sites/all/modules/custom/widget_framework/widget/widget.module
1) Added top ten contracts by disbursement amount.
2) Added top ten vendors by disbursement amount.
3) update total spending across years x-axis labels and title.
4) updated drupal configuration to update and rearrange visualizations.
=> Feature/nycchkbk 9330 - Nycha spending visualizations

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_4.json
Update query for top 10 responsibility centers
=> NYCCHKBK - 9326  nycha contracts visualizations - top ten responsibility centers

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1012.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1027.json
NYCCHKBK - 9265 -
1)  section8 (invoice discount amount, withheld amount and billed amount) all data hyphen
2) invoice discount amount , withheld amount and billed amount show as is for all other categories
3) billed amount mapped to line_net_amount. 
4) All changes also reflected in export data.
=> NYCCHKBK - 9265 - nycha spending transactions data display

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_1.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_2.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_3.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_4.json
Query update for years comparison by agreement types
Top ten responsibility center sql query modification.
=> NYCCHKBK - 9236 - Nycha contracts visulizations update

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_top_navigation.tpl.php
Update nycha spending transactions static text for vendor filter.
Added arrow for nycha spending top navigation on selction.
=> Feature/nycchkbk 9334 - nycha spending vendor filter static text

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_3.json
=> NYCCHKBK - 9042 -  nycha contracts visulizations 

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_across_years.json
1) Display  sum of invoice amount for null category. 
2) Mapped payroll to check amount and all other category to invoice amount
3) Removed x axis values.
4) Sort by years
=> NYCCHKBK - 9328 -  Nycha spending spending across years.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_1.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_2.json
Nycha spending visualizations vendor filter fixed.
=> NYCCHKBK - 9328 -  Nycha spending visualizations vendor filter fixed.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_2.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_visual_1.json
Updated links for top ten contracts by disbursement amount.
=> Feature/nycchkbk 9330 - nycha spending top ten disbursements 

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_4.json
Removed cursor for top ten responsibility center bar chart.
=> Feature/nycchkbk -9236 Nycha contract visualisations

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_1.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_2.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_4.json
NYCCHKBK -9338  Nycha payroll visualizations title links for all charts with title data. Disabled link for others.
=> Feature/nycchkbk 9338 Nycha payroll visualizations title links for all charts with title data.

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/nychaSpending/NychaSpendingWidgetService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_presentation_layer/checkbook_views/checkbook_view_configs/landing_page_widgets/nycha_spending/nycha_contracts_view.json
NYCCHKBK -9371  Nycha spending top 5 contract id link to display in new window and show nycha contract details for the particular id.
=> NYCCHKBK -9371  Nycha spending top 5 contract id link 

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/transactions_page_widgets/1012.json
Nycha spending billed amount format added.
=> NYCCHKBK  9387  Nycha spending billed amount format added.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/nycha_contracts_visual_3.json
NYCCHKB-9042  Nycha contracts Applied vendor, award method, contract size and industry filter for years comparison across agreement types . PO agreement type displayed on top in the stacked charts.
=> NYCCHKB-9042  Nycha contracts years comparison by agreement types.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_across_years.json
nycha spending across years visulaization grid view order by year (desc).
=> NYCCHKBK - 9353 - nycha spending across years visulaization grid view

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_spending/charts/nycha_spending_across_years.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_4.json
Nycha payroll overtime across years grid view sort.
=> Feature/nycchkbk 9397 - nycha payroll overtime across years grid view sort

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_3.json
nycha payroll employees across years tooltip theming issue fixed.
=> NYCCHKBK - 9398 - nycha payroll employees across years tooltip theming

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_1.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_2.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_3.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/charts/payroll_nycha_visual_4.json
NYCCHKBK 9363 - Update the filter parameters for all nycha payroll visulizations. Update drupal configuration for display of right charts on on clicking title link in charts.
=> NYCCHKBK 9363 - Update the filter parameters for all nycha payroll visualizations

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/NychaSpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php
NYCCHKBK 9377 - NYCHA spending total amount spent for the fy static content.
=> NYCCHKBK 9377 - NYCHA spending total amount spent for the fy 

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/checkbook_datafeeds_contracts.inc
Datafeeds display all year in search criteria sections for all three datasource. Disabling display of  contract includes sub vendor field for default search
=> NYCCHKBK-9536 - Datafeeds display all year in search criteria sections.

source/webapp/sites/all/modules/custom/checkbook_advanced_search_autocomplete/includes/checkbook_advanced_search_autocomplete_functions.inc, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/year_list.tpl.php
Reverts NYCComptroller/Checkbook#1668
=> Revert "Feature/nycchkbk 9600"

source/webapp/sites/all/modules/custom/checkbook_api/config/payroll_nycha.json, source/webapp/sites/all/modules/custom/checkbook_api/criteria/AbstractAPISearchCriteria.php, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/checkbook_datafeeds_payroll.inc
Reverts NYCComptroller/Checkbook#1678
=> Revert "Feature/nycchkbk 9649"

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/NychaSpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/SpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/nycha_spending_bottom_slider.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/spending/spending_bottom_slider.tpl.php
Reverting changes made in 9710 - NYCHA and Citywide spending bottom slider name update for Others category.
=> feature/NYCCHKBK-9709 - Adding exception for Contract title display.

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/contract/NYCHAContractsUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/NychaSpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/nycha_spending/transactions_summary.tpl.php
Refactoring Nycha spending and Nycha Contract code.
=> Feature/nycchkbk 9728 - NYCHA invoiced amount link static amount query update.

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/data/ContractsDataService.php
Nyedc landing page widget data display issue for Oge master agreements contract modifications.
=> feature/NYCCHKBK-9331 - Nyedc landing page widget data display issue

source/webapp/sites/all/modules/custom/checkbook_api/handler/AbstractDataHandler.php
Reverts NYCComptroller/Checkbook#1796
=> Revert "NYCCHKBK-9787: Apply adjustSQL for XML/CSV download"

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/317.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/336.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/payroll/transaction_page_widgets/337.json, source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook/cube-payroll_employee_agency.json, source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook_nycha/cube-payroll_employee_agency_basis.json
Fixed the payroll amount value sorting for Citywide, Nycha transaction pages and advanced search transaction results and export results.
=> Feature/nycchkbk 8925 - Payroll all amount values sorting fix.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/567.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/568.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/569.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/570.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/agency_budget/571.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/nyc_budget/263.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/nyc_budget/558.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/nyc_budget/559.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/nyc_budget/560.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/landing_page_widgets/nyc_budget/561.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/transaction_page_widgets/575.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/transaction_page_widgets/576.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/transaction_page_widgets/577.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/visualizations/260.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/visualizations/290.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/budget/visualizations/468.json
Department url parameter mapped to department code. Update the department links parameter to map to department code in transactions pages and visualizations. Updated filters in visualizations
=> Feature/nycchkbk 9791 - Department url parameter mapped to department code

source/webapp/sites/all/modules/custom/checkbook_solr/src/checkbook_solr_query.class.inc
Smart search partial search verified for all 3 domains and conditions as mentioned in the document provided in the ticket.
=> Feature/nycchkbk 10008 - Citywide smart search contract id partial text search

source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/checkbook_advanced_search.inc, source/webapp/sites/all/modules/custom/checkbook_advanced_search_autocomplete/includes/checkbook_advanced_search_autocomplete_functions.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/checkbook_datafeeds_budget.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/checkbook_datafeeds_revenue.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/spending.js, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/CheckbookDateUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/includes/checkbook_project.inc, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/fiscal_year_list.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/year_list.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/home/top_slider/472.json
Moved Current Fiscal years and Starting fiscal/calendar years to server variables
=> NYCCHKBK-10043: Refactoring and code clean-up date filter options

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_solr/src/checkbook_solr_query.class.inc
Reverts NYCComptroller/Checkbook#2029
Reverting the request to implement changes.
=> Revert "Feature/nycchkbk 9920 - Advanced search results for terms with space."

source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/nycha_spending.tpl.php
Update to process '0' amount to show it as '-', instead of '$0.0' in Nycha Spending smart search
=> NYCCHKBK 9851: Update to show amount as '-' instead of '$0.0'

source/webapp/sites/all/modules/custom/checkbook_project/templates/new-features.html
Update file for adding comments, and new data (updated data on dev2 environment via Drupal).
=> Update file for comments and new data

source/webapp/sites/all/modules/custom/checkbook_solr/src/checkbook_solr_query.class.inc
=> feature - NYCCHKBK - 9920 - Smart search and advanced search autocompletes update facet prefix for array fields.

source/webapp/sites/all/modules/custom/checkbook_api/checkbook_api.module, source/webapp/sites/all/modules/custom/checkbook_api/config/contracts_nycha.json, source/webapp/sites/all/modules/custom/checkbook_api/config/payroll.json, source/webapp/sites/all/modules/custom/checkbook_api/config/payroll_nycha.json, source/webapp/sites/all/modules/custom/checkbook_api/config/spending_nycha.json
Verified only downloads for small files. Will verify the downloads for larger files and update if changes required.
=> feature - NYCCHKBK - 10169 - Nycha Datafeeds remove hyphens for xml downloads.

source/webapp/sites/all/modules/custom/checkbook_api/checkbook_api.module, source/webapp/sites/all/modules/custom/checkbook_api/config/contracts.json
Need to verify for large file downloads.
=> Feature/nycchkbk 10177 - Citywide datafeeds contracts sql query modifications.

source/webapp/sites/all/modules/custom/checkbook_api/checkbook_api.module, source/webapp/sites/all/modules/custom/checkbook_api/config/payroll.json, source/webapp/sites/all/modules/custom/checkbook_api/config/payroll_nycha.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_revenue/1057.json
Need to verify both csv and xml > 20000 records downloads.
=> Feature nycchkbk 10183 - Payroll(citywide and nycha) datafeeds salaried and non-salaried display in downloads. 

source/webapp/sites/all/modules/custom/checkbook_api/checkbook_api.module, source/webapp/sites/all/modules/custom/checkbook_api/handler/DataSetHandler.php
Verified Advanced search inputs already handles special characters in the widget module.  The commit takes care of 9988 and 9900(payroll special characters issue).
=> Faeture nycchkbk 9988 - Datafeeds input special characters handling.

source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/payroll.tpl.php
Update fiscal year to calendar fiscal year for correctly mapping the data
=> NYCCHKBK-10178: Update fiscal year to calendar fiscal year

source/webapp/sites/all/modules/custom/checkbook_api/config/contracts.json, source/webapp/sites/all/modules/custom/checkbook_api/handler/XMLDataHandler.php
=> Feature/nycchkbk 10177 - Fixing error in contracts json file and removing print statements

source/webapp/sites/all/modules/custom/checkbook_faceted_search/checkbook_faceted_search.module, source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php
=> feature - NYCCHKBK - 10192 - Facet enabling only for url parameters and not ajax paramters.

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/BudgetFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/BudgetFeedNycha.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/contracts/checkbook_datafeeds_contracts.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/payroll/checkbook_datafeeds_payroll.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/RevenueFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/RevenueFeedNycha.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycedc.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycha.class.inc
Add condition to accept "0" in range fields (min and max) for all domains and all data sources in data feeds.
=> NYCCHKBK-10175: All domains/All Data Sources : Search criteria text for range fields

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/BudgetFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/BudgetFeedNycha.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/contracts/checkbook_datafeeds_contracts.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/payroll/checkbook_datafeeds_payroll.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/RevenueFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/RevenueFeedNycha.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedCitywide.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycedc.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycha.class.inc
Change ' Less Than Equal to: $' to ' and Less Than Equal to: $' when both min and max range are selected
=> NYCCHKBK-10175: All domains/All Data Sources : Text changes

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeed.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycha.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/checkbook_datafeeds_spending.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/spending.js, source/webapp/sites/all/themes/checkbook3/css/datafeeds.css
Verified - 
1) results based on the year filter chosen. 
2) previous button data retaining
=> Feature nycchkbk 10046 - Datafeeds spending separate year filter for nycha.

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/BudgetFeedCitywide.class.inc
Add condition to accept '0' in 'Modified Budget' field in Data feeds Budget Citywide
=> NYCCHKBK-10175: Search criteria text for range fields - Add condition to accept '0' in 'Modified Budget' field

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_faceted_search/individual-filter.tpl.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/WidgetUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_budget/transactions_page_widgets/1034.json
Nycha budget - budget_name and budget_type to not display 'n/a' in facets and advanced search and datafeeds form.
=> feature - NYCCHKBK - 10215 - Nycha budget - budget_name and budget_type fix

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/budget/checkbook_datafeeds_budget.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/payroll/checkbook_datafeeds_payroll.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/revenue/checkbook_datafeeds_revenue.inc
Add condition to retain "0" in data feeds form when Previous button is clicked from the results page
=> Nycchkbk 10204: Add condition to retain "0" in data feeds form

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/1064.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/766.json, source/webapp/sites/all/modules/custom/dashboard_platform/checkbook_metamodel/metamodel/metadata/checkbook/subvendor/cube-spending-transactions-subven.json
- Add 'Contract ID' facet to Advanced Search Spending results
=> Feature NYCCHKBK 10217: Advanced Search Spending results

source/webapp/sites/all/modules/custom/checkbook_advanced_search/checkbook_advanced_search.module, source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/checkbook_advanced_search.inc, source/webapp/sites/all/modules/custom/checkbook_advanced_search/includes/contracts_advanced_search.inc
=> feature - 10279 - Advanced search transaction results update for citywide contracts

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js
Clear autocomplete input fields when catastrophic events filter is changed.
=> Nycchkbk 10282 - Advanced search Spending form - clear autocomplete fields

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js
Verified - Advanced search transactions from in chrome and mozilla for results display and loading image display . Need to verify create alert.
=> Feature nycchkbk 9485 - Advanced search/create alert loading gif disappears after first click fix.

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeed.class.inc, source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycha.class.inc
Handled space issue between FY and year number
=> NYCCHKBK 10315: Datafeeds results page - Year spacing issue

source/webapp/sites/all/modules/custom/checkbook_api/handler/CSVDataHandler.php
Handled scenario where we add 'CASE' statements to columns in SQL query
=> NYCCHKBK-10332: Datafeeds - Spending - No Results found for download data

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js
Reverts NYCComptroller/Checkbook#2249
=> Revert "Nycchkbk 10282 - Advanced search Spending form - clear autocomplete fields"

source/webapp/sites/all/themes/checkbook3/js/advanced-search.js
Reverts NYCComptroller/Checkbook#2286
=> Revert "NYCCHKBK-10310 : Advance Search Form Revenue - Revenue Source and Class not updated"

source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/revenue.js
https://github.com/NYCComptroller/Checkbook/pull/2303
=> NYCCHKBK-10347: Data feeds Revenue form - Revert 'autocomplete refresh on catastrophic event filter change' functionality

source/tests/unit/tests/checkbook_project/RequestUtilTest.php
Request Util test case update.
=> Feature nycchkbk 10313(update)

source/webapp/sites/all/modules/custom/checkbook_api/config/contracts.json, source/webapp/sites/all/modules/custom/checkbook_datafeeds/config/checkbook_datafeeds_contracts_column_options.json, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php
Need to verify large file download results.
=> feature - 10436 - MWBE Contracts citywide datafeeds results configuration update to include woman owned and emerging columns.

source/webapp/sites/all/modules/custom/checkbook_api/checkbook_api.module
Verified downloads for different inputs.
=> feature - 10449 - Citywide datafeeds query fix.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe/706.json, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/common/MinorityTypeService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_infrastructure_layer/utilities/MappingUtilities.php
- Fix spending transaction pages widget node
- Add 'native' & 'emerging' to mapping services / utility classes
=> feature-NYCCHKBK-10474: Add ‘Native’ and ‘Emerging’ categories in mapping services/classes

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/RequestUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php
Add 'Native' and 'Emerging' categories to Top navigation menu and update Total M/WBE link in M/WBE and Sub Vendors(M/WBE) Dashboards
=> Feature NYCCHKBK-10471 : Add 'Native' and 'Emerging' categories to Top navigation menu and update Total M/WBE link

source/tests/unit/tests/checkbook_project/CustomURLHelperTest.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/CustomURLHelper.php
- Add Unit test cases for Custom URL helper service
- Fix code smells in Custom URL helper service
=> Feature NYCCHKBK-10312: Add PHP Unit test class for Custom URL Helper service

source/webapp/sites/all/modules/custom/checkbook_api_ref_files/config/ref_files_list.json, source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_revenue/1055.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/nycha_revenue/1056.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_revenue/charts/revenue_programs.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_revenue/charts/revenue_projects.json, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_domain/config/sql/revenue/nycha_revenue.xml
For NYCHA Revenue API, exclude 'DEFAULT' from API code ref file for project and program fields
=> Feature nycchkbk 10532- NYCHA Revenue - Hide ‘no program assigned’ and ‘no project assigned’ in UI

source/webapp/sites/all/modules/custom/checkbook_datafeeds/includes/spending/SpendingFeedNycha.class.inc
Testing the issue will revert the changes later.
=> Feature nycchkbk 10092 - email alignment for datafeeds

source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/revenue.js, source/webapp/sites/all/modules/custom/checkbook_datafeeds/js/spending.js, source/webapp/sites/all/themes/checkbook3/js/advanced-search.js
1. Year Filter Refactoring to accommodate future years for Catastrophic events for Revenue and spending domains in
- data feeds
- advanced search
2. Removed duplicate code from advanced search for spending domain
=> Feature nycchkbk 10577 : Year Filter Refactoring to accommodate future years for Catastrophic events

source/webapp/sites/all/modules/custom/checkbook_api_ref_files/config/ref_files_list.json
Reverts NYCComptroller/Checkbook#2451
=> Revert "Feature nycchkbk 9894 : API Cron Jobs- Updates - Exclude unnecessary API ref file queries"

source/webapp/sites/all/modules/custom/checkbook_datafeeds/checkbook_datafeeds.module
Need to verify in the dev server.
=> feature - 10092 - Nycha Spending datafeeds notification and confirmation email alignment issue.

source/webapp/sites/all/modules/custom/checkbook_api_ref/config/ref_file_sql.json
Add ref file queries for the following fields in Contract API page:
- contract_includes_sub_vendors
- sub_vendor_status_in_pip
=> Defect nycchkbk 10626 : Add ref file queries (MWBE)

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/contract/ContractUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/SpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/NodeSummaryUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/WidgetUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/nycha_contracts/charts/amounts_trends_by_borough.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsUrlService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsWidgetService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsWidgetVisibilityService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/widget/WidgetSqlService.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_infrastructure_layer/constants/CommonConstants.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_presentation_layer/checkbook_controllers/widget_controller/WidgetController.php, source/webapp/sites/all/modules/custom/log4drupal/Log-1.12.x/Log.php, source/webapp/sites/all/modules/custom/log4drupal/Log-1.12.x/Log/composite.php, source/webapp/sites/all/modules/custom/log4drupal/Log-1.12.x/Log/mdb2.php, source/webapp/sites/all/modules/custom/log4drupal/Log-1.12.x/Log/sql.php
=> NYCCHKBK-10326: Fixed critical bugs with syntax and parameter types.

source/webapp/sites/all/modules/custom/checkbook_project/php_widgets/contracts_navigation.tpl.php
Applicable only to prime vendor filters on landing pages.
=> feature - 10639 - Top navigation disabling spending/contracts when prime vendor filter is applied and it is mwbe certified.

source/webapp/sites/all/modules/custom/checkbook_api_ref/theme/api-ref.email.tpl.php
Remove ✅ symbol from email theme file. Only show ✅  when files are updated.
=> Feature nycchkbk 9894 : Remove ✅ symbol from email theme file

source/webapp/sites/all/modules/custom/checkbook_api_ref/includes/CheckbookApiRef.class.php
Add cron timeline setup for dev and prod/stage environments
=> Feature NYCCHKBK 9894 : Add cron timeline setup

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/spending/SpendingUtil.php, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/contracts/transaction_page_widgets/pending_expense_and_revenue/714.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/contracts/transaction_page_widgets/revenue/mwbe/all_transactions/688.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe/707.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/sub-vendors/724.json
- Fix Contracts transaction page exports alignment issue
- Fix Spending transaction pages issue (due to incorrect function signature)
=> Defect nycchkbk 10711 : Contracts transaction page exports alignment issue

source/webapp/sites/all/modules/custom/checkbook_project/customclasses/util/MappingUtil.php
- For top navigation, Native and Emerging will appear in all pages except for when filters applied
=> Defect nycchkbk 10608: Add ‘Native’ and ‘Emerging’ categories to M/WBE and Sub Vendors(M/WBE) Dashboard

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe/707.json
- Fix export issue with associated prime vendor name field in Spent to Date links page
- Fix theming issue with associated prime vendor name field on UI
=> Defect nycchkbk 10734: Fix export issue with associated prime vendor name field in Spent to Date links page

source/tests/unit/tests/checkbook_widget_redesign/SpendingTest.php, source/webapp/sites/all/modules/custom/checkbook_project/includes/checkbook_project.inc
Fixed Contracts/Spending advanced search all years fix the year value in the transactions vendor links and also the phpunit test case.
=> Feature nycchkbk 10777 - Contracts/Spending advanced search all years fix the year value in the transactions vendor links.

source/webapp/sites/all/modules/custom/checkbook_smart_search/templates/spending.tpl.php
- Add condition to form correct URL for vendor name which is 'prime vendor' and 'non minority'
=> Defect NYCCHKBK-10805 : Smart Search Results - Vendor Hyperlinks issue

source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/contracts/ContractsUrlService.php
Removed duplicate facets in pending mwbe transaction pages and fixed the proper filter application for transactions results
=> Feature nycchkbk 10888 -  Updating mwbe url parameter for pending contracts transactions.

INSTALL.md
=> NYCCHKBK-10254: High charts library update to 9.3.2

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/766.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/spending/transaction_page_widgets/mwbe/706.json
Display N/A for spending transaction(details/advanced search) for certain columns based on rules provided in ticket 11006  and also update exports accordingly.
=> Feature nycchkbk 11006 - Display N/A for spending transaction(details/advanced search) for certain columns.

source/tests/unit/tests/checkbook_widget_redesign/SpendingTest.php, source/webapp/sites/all/modules/custom/checkbook_widget_redesign/checkbook_business_layer/checkbook_services/spending/SpendingUrlService.php
Verified few details and ytd links for the above changes.
=> feature -NYCCHKBK - 11073 - Passing correct vendor parameter for sub vendor ytd and sub vendor details links transactions

source/webapp/sites/all/modules/custom/checkbook_project/includes/checkbook_project.inc
Prime vendor name links from the contract id page should carry the latest mwbe parameter.
=> Feature nycchkbk 8055 - Prime vendor name link update from contract id details page.

source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/1066.json, source/webapp/sites/all/modules/custom/checkbook_project/widget_config/narrow_down_filters/spending/mwbe/1065.json, source/webapp/sites/all/modules/dashboard_platform/data_controller_datasource/sql/core/query/datasource/operator/handler/SQL_NotEqualOperatorHandler.php
Reverting the previous change made in the NotEqualOpertorhandler as it is breaking the visualizations query. Need to refactor and create a handler for budget name code facet issue. (11004)
=> Feature nycchkbk 11004(revert) - Reverting previous change.

source/webapp/sites/all/modules/dashboard_platform/data_controller/common/object/comparator/handler/PropertyBasedComparator.php
Fixed code deprecation in newer PHP version - To verify environment issue
=> NYCCHKBK-11091: Fixed code deprecation

source/tests/functional/NYCAutomationTest/pom.xml, source/tests/functional/NYCAutomationTest/src/main/java/helpers/Driver.java
Updates selenium version and maven compiler versions
=> Updated maven compiler version
